// Comentarios de la tabla de variables de los ejemplos (lib/examples.js): qué es cada señal y qué
// hace cada etapa. Mejor explicar de más: son para aprender.
// { [id del ejemplo]: { variables: { nombre: comentario }, steps: { etiqueta: comentario } } }

export const EXAMPLE_COMMENTS = {
  'marcha-paro': {
    variables: {
      Marcha: 'Pulsador verde NA: arranca el motor',
      Paro: 'Pulsador rojo NC: vale 1 sin pulsar',
      Motor: 'Contactor del motor',
      Piloto: 'Luz verde: motor en marcha',
    },
    steps: { 0: 'Reposo: motor parado', 1: 'Motor en marcha' },
  },
  contador: {
    variables: {
      Marcha: 'Pulsador: empieza a contar',
      P: 'Pulsador que se cuenta (por flanco)',
      Reset: 'Pulsador: vuelve a empezar',
      Luz: 'Se enciende a la 3.ª pulsación',
      C: 'Contador de pulsaciones (palabra)',
    },
    steps: { 0: 'Reposo: pone C a 0 al entrar', 1: 'Esperando pulsaciones', 2: 'Suma 1 a C (dura un instante)', 3: 'Tercera pulsación: luz encendida' },
  },
  garaje: {
    variables: {
      Abrir: 'Pulsador o mando a distancia',
      Abierta: 'Final de carrera: puerta arriba',
      Cerrada: 'Final de carrera: puerta abajo',
      Foto: 'Fotocélula: 1 si hay un obstáculo',
      Subir: 'Motor de la puerta: subir',
      Bajar: 'Motor de la puerta: bajar',
      Luz: 'Luz de aviso mientras se mueve',
      '5s/X2': 'Tiempo que la puerta queda abierta',
      Poner_coche: 'Solo planta: pone un coche delante',
    },
    steps: { 0: 'Puerta cerrada, en reposo', 1: 'Abriendo', 2: 'Abierta: espera 5 s', 3: 'Cerrando (vigilando la fotocélula)' },
  },
  taladradora: {
    variables: {
      Marcha: 'Pulsador de marcha',
      Pieza: 'Detector: hay pieza colocada',
      Fc_arriba: 'Final de carrera: broca arriba',
      Fc_abajo: 'Final de carrera: broca abajo',
      Motor_broca: 'Motor de giro de la broca',
      Bajar: 'Electroválvula: bajar la broca',
      Subir: 'Electroválvula: subir la broca',
      '2s/X2': 'Tiempo de repaso del agujero',
    },
    steps: { 0: 'Reposo, broca arriba', 1: 'Bajando y taladrando', 2: 'Repaso de 2 s abajo', 3: 'Subiendo' },
  },
  cilindros: {
    variables: {
      Marcha: 'Pulsador de marcha (un ciclo)',
      a0: 'Detector: cilindro A dentro',
      a1: 'Detector: cilindro A fuera',
      b0: 'Detector: cilindro B dentro',
      b1: 'Detector: cilindro B fuera',
      'A+': 'Electroválvula: sacar A',
      'A-': 'Electroválvula: meter A',
      'B+': 'Electroválvula: sacar B',
      'B-': 'Electroválvula: meter B',
    },
    steps: { 0: 'Reposo: A y B dentro', 1: 'Sale A', 2: 'Sale B', 3: 'Entra A', 4: 'Entra B' },
  },
  pickplace: {
    variables: {
      Marcha: 'Pulsador de marcha (un ciclo)',
      x0: 'Detector: brazo X recogido',
      x1: 'Detector: brazo X fuera',
      z0: 'Detector: brazo Z arriba',
      z1: 'Detector: brazo Z abajo',
      Cogida: 'Vacuostato: la ventosa tiene pieza',
      'X+': 'Electroválvula: sacar X',
      'X-': 'Electroválvula: recoger X',
      'Z+': 'Electroválvula: bajar Z',
      'Z-': 'Electroválvula: subir Z',
      V: 'Vacío de la ventosa',
    },
    steps: {
      0: 'Reposo: X recogido, Z arriba',
      1: 'Baja Z con vacío hasta coger',
      2: 'Sube Z con la pieza',
      3: 'X lleva la pieza',
      4: 'Baja Z en el destino',
      5: 'Suelta la pieza (sin vacío)',
      6: 'Sube Z',
      7: 'X vuelve',
    },
  },
  clasificadora: {
    variables: {
      Marcha: 'Interruptor de marcha',
      Metal: 'Detector inductivo: pieza de metal',
      M: 'Motor de la cinta',
      D: 'Desviador: saca la pieza de metal',
      '1.5s/X2': 'Tiempo con el desviador activo',
    },
    steps: { 0: 'Parada', 1: 'Cinta en marcha', 2: 'Desviando una pieza de metal' },
  },
  'clasificadora-tamano': {
    variables: {
      Marcha: 'Interruptor de marcha',
      Metal: 'Detector inductivo: pieza de metal',
      Grande: 'Detector alto: solo ve piezas grandes',
      M: 'Motor de la cinta',
      D1: 'Desviador 1: rechazo (metal)',
      D2: 'Desviador 2: plástico grande',
      '1.5s/X2': 'Tiempo con D1 activo',
      '1.5s/X3': 'Tiempo con D2 activo',
    },
    steps: { 0: 'Parada', 1: 'Cinta en marcha', 2: 'Rechazando metal (D1)', 3: 'Sacando plástico grande (D2)' },
  },
  ascensor: {
    variables: {
      L0: 'Llamada desde la planta 0',
      L1: 'Llamada desde la planta 1',
      L2: 'Llamada desde la planta 2',
      P0: 'Final de carrera: cabina en planta 0',
      P1: 'Final de carrera: cabina en planta 1',
      P2: 'Final de carrera: cabina en planta 2',
      Subir: 'Motor: subir la cabina',
      Bajar: 'Motor: bajar la cabina',
    },
    steps: { 0: 'Cabina parada esperando llamadas', 1: 'Bajando a la planta 0', 2: 'Subiendo de la 0 a la 1', 3: 'Subiendo a la planta 2', 4: 'Bajando de la 2 a la 1' },
  },
  'doble-puesto': {
    variables: {
      Marcha: 'Pulsador de marcha',
      t0: 'Detector: taladro arriba',
      t1: 'Detector: taladro abajo',
      k0: 'Detector: marcador arriba',
      k1: 'Detector: marcador abajo',
      'T+': 'Electroválvula: bajar el taladro',
      'T-': 'Electroválvula: subir el taladro',
      Broca: 'Motor de giro de la broca',
      'K+': 'Electroválvula: bajar el marcador',
      'K-': 'Electroválvula: subir el marcador',
    },
    steps: {
      0: 'Reposo',
      1: 'Taladrando (baja con giro)',
      2: 'Sube el taladro',
      3: 'Taladro terminado: espera',
      4: 'Marcando (baja)',
      5: 'Sube el marcador',
      6: 'Marcado terminado: espera',
    },
  },
  'luz-pulsador': {
    variables: { P: 'Pulsador: encender y apagar', Luz: 'Lámpara' },
    steps: { 0: 'Luz apagada', 1: 'Luz encendida' },
  },
  'estrella-triangulo-plc': {
    variables: {
      Marcha: 'Pulsador de marcha',
      Paro: 'Pulsador de paro (NC)',
      Linea: 'Contactor de línea KM1',
      Triangulo: 'Contactor de triángulo KM2',
      Estrella: 'Contactor de estrella KM3',
      '5s/X1': 'Tiempo en estrella',
      '0.5s/X2': 'Pausa entre estrella y triángulo',
    },
    steps: { 0: 'Motor parado', 1: 'Arranque en estrella', 2: 'Pausa (ni estrella ni triángulo)', 3: 'Marcha en triángulo' },
  },
  'cinta-reversible': {
    variables: {
      Derecha: 'Pulsador: llevar a la derecha',
      Izquierda: 'Pulsador: llevar a la izquierda',
      Paro: 'Pulsador de paro (NC)',
      Fin_dcha: 'Detector: pieza en el extremo derecho',
      Fin_izq: 'Detector: pieza en el extremo izquierdo',
      Poner: 'Pulsador: poner una pieza',
      Adelante: 'Contactor KM1: hacia la derecha',
      Atras: 'Contactor KM2: hacia la izquierda',
    },
    steps: { 0: 'Cinta parada', 1: 'Hacia la derecha', 2: 'Hacia la izquierda' },
  },
  'dahlander-plc': {
    variables: {
      Marcha: 'Pulsador de marcha',
      Paro_ciclo: 'Pulsador: parar (frenando en lenta)',
      Seta: 'Seta de emergencia (NC)',
      Rearme: 'Pulsador de rearme',
      Lenta: 'Contactor KM1: velocidad lenta (triángulo)',
      Rapida: 'Contactor KM2: velocidad rápida',
      Puente: 'Contactor KM3: puente de la doble estrella',
      Alarma: 'Piloto de emergencia',
      '4s/X1': 'Tiempo en lenta al arrancar',
      '3s/X3': 'Tiempo en lenta al parar',
    },
    steps: { 0: 'Motor parado', 1: 'Arranque en lenta', 2: 'Velocidad rápida', 3: 'Frenando en lenta', 10: 'Vigilando', 11: 'Emergencia: producción forzada a parar', 12: 'Rearme: producción al inicio' },
  },
  'cinta-variador': {
    variables: {
      Marcha: 'Interruptor de marcha',
      Pieza: 'Detector: pieza en la zona de carga',
      Avance: 'Orden de marcha al variador (DI1)',
      Velocidad: 'Consigna de velocidad al variador (AI1, 0-50 Hz)',
    },
    steps: { 0: 'Cinta parada', 1: 'Rápida (50 Hz)', 2: 'Lenta (15 Hz) con pieza en carga' },
  },
  'semaforo-peatones': {
    variables: {
      Pulsador: 'Pulsador de peatones',
      VerdeC: 'Coches: verde',
      AmbarC: 'Coches: ámbar',
      RojoC: 'Coches: rojo',
      VerdeP: 'Peatones: verde',
      RojoP: 'Peatones: rojo',
      Espere: 'Piloto: petición recibida',
      '10s/X0': 'Verde mínimo de los coches',
      '3s/X1': 'Tiempo en ámbar',
      '1s/X2': 'Todo en rojo (seguridad)',
      '8s/X3': 'Verde de los peatones',
    },
    steps: { 0: 'Coches en verde', 1: 'Coches en ámbar', 2: 'Todo en rojo', 3: 'Peatones en verde', 10: 'Sin petición', 11: 'Petición recordada' },
  },
  aparcamiento: {
    variables: {
      Entra: 'Detector: entra un coche',
      Sale: 'Detector: sale un coche',
      Libre: 'Piloto: hay plazas',
      Completo: 'Piloto: aparcamiento lleno',
      C: 'Coches dentro (contador)',
    },
    steps: { 0: 'Esperando coches', 1: 'Suma un coche', 2: 'Resta un coche' },
  },
  'silo-vibrador': {
    variables: {
      Marcha: 'Pulsador: descargar el silo',
      Lleno: 'Detector de silo lleno',
      Vacio: 'Detector de silo vacío',
      Descarga: 'Electroválvula de descarga',
      Aviso: 'Sirena de aviso (2 s)',
      Vibrador: 'Motor vibrador (desde los 4 s)',
      Llenar: 'Electroválvula de llenado',
      '2s/X1': 'Duración del aviso',
      '4s/X1': 'Retardo del vibrador',
    },
    steps: { 0: 'Silo lleno, en espera', 1: 'Descargando', 2: 'Llenando' },
  },
  'dos-carros': {
    variables: {
      Pide_A: 'Pulsador: el carro A pide el tramo',
      Pide_B: 'Pulsador: el carro B pide el tramo',
      a0: 'Carro A fuera del tramo',
      a1: 'Carro A al final del tramo',
      b0: 'Carro B fuera del tramo',
      b1: 'Carro B al final del tramo',
      'A+': 'Carro A: entrar',
      'A-': 'Carro A: volver',
      'B+': 'Carro B: entrar',
      'B-': 'Carro B: volver',
    },
    steps: { 10: 'A en reposo', 11: 'A entra en el tramo', 12: 'A vuelve', 30: 'B en reposo', 31: 'B entra en el tramo', 32: 'B vuelve' },
  },
  'taladradora-verificacion': {
    variables: {
      Marcha: 'Pulsador de marcha',
      Pieza: 'Interruptor: pieza colocada',
      Fc_abajo: 'Final de carrera: broca abajo',
      Fc_arriba: 'Final de carrera: broca arriba',
      Verificacion: 'Selector: marcha de verificación',
      Paso: 'Pulsador: avanzar un paso',
      Motor_broca: 'Motor de la broca',
      Bajar: 'Bajar la broca',
      Subir: 'Subir la broca',
      Produccion: 'Piloto: producción normal',
      Modo_verif: 'Piloto: verificación',
      '2s/X2': 'Repaso en el fondo',
    },
    steps: { 0: 'Reposo', 1: 'Baja taladrando', 2: 'Repasa', 3: 'Sube', 20: 'Producción normal (A1/F1)', 21: 'Marcha de verificación (F5)' },
  },
  'dosificacion-peso': {
    variables: {
      Marcha: 'Pulsador: dosificar',
      Peso: 'Báscula de la tolva (4-20 mA)',
      Consigna: 'Kilos que hay que añadir',
      Gruesa: 'Válvula de llenado grueso',
      Fina: 'Válvula de llenado fino',
      Descarga: 'Válvula de descarga',
      Tara: 'Peso al empezar (tara)',
      Corte: 'Peso al que se pasa a fino',
      Meta: 'Peso final',
      Fin: 'Peso al que se acaba la descarga',
      '2s/X3': 'Estabilización',
    },
    steps: { 0: 'Reposo', 1: 'Llenado grueso', 2: 'Llenado fino', 3: 'Estabilización', 4: 'Descarga' },
  },
  semaforo: {
    variables: {
      Rojo: 'Luz roja',
      Ámbar: 'Luz ámbar',
      Verde: 'Luz verde',
      '10s/X0': 'Tiempo en rojo',
      '8s/X1': 'Tiempo en verde',
      '3s/X2': 'Tiempo en ámbar',
    },
    steps: { 0: 'Rojo', 1: 'Verde', 2: 'Ámbar' },
  },
  mezcladora: {
    variables: {
      Marcha: 'Pulsador: producir una mezcla',
      Limpieza: 'Pulsador: ciclo de lavado',
      Nivel_A: 'Sensor: depósito A lleno',
      Nivel_B: 'Sensor: depósito B lleno',
      Vacio: 'Sensor: depósitos vacíos',
      Fin_lavado: 'Pulsador: lavado terminado',
      Llenar_A: 'Válvula de llenado de A',
      Llenar_B: 'Válvula de llenado de B',
      Mezclar: 'Motor del agitador',
      Vaciar: 'Válvula de vaciado',
      Lavar: 'Ciclo de lavado en marcha',
      '30s/X5': 'Tiempo de mezcla',
    },
    steps: {
      0: 'Reposo: elegir producir o limpiar',
      1: 'Llenando A',
      2: 'Llenando B',
      3: 'A lleno: espera a B',
      4: 'B lleno: espera a A',
      5: 'Mezclando 30 s',
      6: 'Vaciando',
      7: 'Lavando',
    },
  },
  emergencia: {
    variables: {
      Marcha: 'Pulsador de marcha',
      Emergencia: 'Pulsador de emergencia (1 = pulsado)',
      Rearme: 'Pulsador de rearme tras la emergencia',
      Fc_delante: 'Final de carrera: carro delante',
      Fc_detras: 'Final de carrera: carro detrás',
      Avanzar: 'Motor: avanzar el carro',
      Retroceder: 'Motor: retroceder el carro',
      Alarma: 'Luz de alarma',
    },
    steps: {
      10: 'G1: vigilando la emergencia',
      11: 'G1: emergencia, G2 sin etapas',
      12: 'G1: rearme, G2 a su inicio',
      0: 'G2: reposo',
      1: 'G2: avanzando',
      2: 'G2: retrocediendo',
    },
  },
  'manual-auto': {
    variables: {
      Auto: 'Selector: 0 manual, 1 automático',
      Ciclo: 'Pulsador: un ciclo en automático',
      Avanzar: 'Pulsador manual: sacar A',
      Retroceder: 'Pulsador manual: meter A',
      a0: 'Detector: cilindro A dentro',
      a1: 'Detector: cilindro A fuera',
      'A+': 'Electroválvula: sacar A',
      'A-': 'Electroválvula: meter A',
      Luz_auto: 'Luz: modo automático',
    },
    steps: { 20: 'GC: manual (GP forzado a su inicio)', 21: 'GC: automático', 0: 'GP: reposo', 1: 'GP: sale A', 2: 'GP: entra A' },
  },
  'gemma-linea': {
    variables: {
      Marcha: 'Pulsador de marcha',
      Paro: 'Pulsador: parar a fin de ciclo',
      Rearme: 'Pulsador de rearme',
      Seta_ok: 'Seta NC: 1 si no está pulsada',
      a0: 'Detector: cilindro A dentro',
      a1: 'Detector: cilindro A fuera',
      'A+': 'Electroválvula: sacar A',
      'A-': 'Electroválvula: meter A',
      Luz_marcha: 'Luz: en producción',
      Alarma: 'Luz de alarma (emergencia)',
    },
    steps: {
      20: 'A1: parada en el estado inicial',
      21: 'F1: producción normal',
      22: 'A2: parada a fin de ciclo',
      23: 'D1: parada de emergencia',
      24: 'A6: vuelta al estado inicial',
      0: 'GP: reposo',
      1: 'GP: sale A',
      2: 'GP: entra A',
    },
  },
  horno: {
    variables: {
      Marcha: 'Interruptor de marcha',
      Consigna: 'Potenciómetro: temperatura deseada',
      Temp: 'Sonda de temperatura del horno',
      R: 'Resistencia calefactora',
      Alarma: 'Luz: sobretemperatura (≥ 180 °C)',
      Alto: 'Umbral de apagado: consigna + 5',
      Bajo: 'Umbral de encendido: consigna − 5',
    },
    steps: { 0: 'Parado', 1: 'Calentando (calcula Alto)', 2: 'Sin calentar (calcula Bajo)', 10: 'Alarma: vigilando', 11: 'Alarma: sobretemperatura' },
  },
  'deposito-nivel': {
    variables: {
      Marcha: 'Interruptor: regulación en marcha',
      Consumir: 'Interruptor: abrir el consumo',
      Nivel: 'Sensor de nivel 4–20 mA (0–100 %)',
      Bomba: 'Bomba de llenado',
      Salida: 'Válvula de consumo',
      Alarma_alta: 'Luz: nivel ≥ 95 %',
      Alarma_baja: 'Luz: nivel ≤ 5 %',
    },
    steps: {
      0: 'Regulación parada',
      1: 'Esperando a que baje al 30 %',
      2: 'Bombeando hasta el 80 %',
      10: 'Consumo cerrado',
      11: 'Consumo abierto',
      20: 'Vigilando el nivel alto',
      21: 'Nivel alto',
      30: 'Vigilando el nivel bajo',
      31: 'Nivel bajo',
    },
  },
  'elevador-frente': {
    variables: {
      Marcha: 'Interruptor de marcha',
      Rearme: 'Pulsador de rearme tras un atasco',
      S1: 'Detector óptico: pieza en el elevador',
      b0: 'Final de carrera: elevador abajo',
      b1: 'Final de carrera: elevador arriba',
      c0: 'Final de carrera: empujador recogido',
      c1: 'Final de carrera: empujador fuera',
      Soltar: 'Alimentador: suelta una pieza',
      M1: 'Motor de la cinta 1 (llegada)',
      M2: 'Motor de la cinta 2 (salida)',
      B: 'Electroválvula: subir el elevador',
      C: 'Electroválvula: sacar el empujador',
      Alarma: 'Luz de atasco',
      '3s/X2': 'Vigilancia: tiempo máximo de subida',
      '3s/X3': 'Vigilancia: tiempo máximo de empuje',
    },
    steps: {
      0: 'Esperando marcha (todo en reposo)',
      1: 'Soltando una pieza y llevándola al elevador',
      2: 'Subiendo la pieza',
      3: 'Empujando la pieza a la cinta 2',
      4: 'Bajando el elevador y recogiendo el empujador',
      5: 'Atasco del elevador',
      6: 'Atasco del empujador',
    },
  },
  macroetapa: {
    variables: {
      Marcha: 'Pulsador de marcha',
      Nivel: 'Sensor: dosis completa',
      Retirar: 'Pulsador: retirar el producto',
      Fc_expulsion: 'Final de carrera: expulsión hecha',
      Llenar: 'Válvula de dosificación',
      Calentar: 'Resistencia calefactora',
      Expulsar: 'Cilindro de expulsión',
      Listo: 'Luz: producto listo',
      '20s/X11': 'Tiempo de calentamiento',
    },
    steps: { 0: 'Reposo', M1: 'Macroetapa: dosificar y calentar', 2: 'Expulsando', E1: 'Entrada de M1: llenar', 11: 'Calentando 20 s', S1: 'Salida de M1: listo' },
  },
  'cargador-gravedad': {
    variables: {
      Marcha: 'Pulsador de marcha (un lote)',
      Hay_pieza: 'Detector: pieza abajo en el cargador',
      a0: 'Detector: expulsor dentro',
      a1: 'Detector: expulsor fuera',
      'A+': 'Electroválvula: sacar el expulsor',
      'A-': 'Electroválvula: meter el expulsor',
      Cinta: 'Motor de la cinta de salida',
      Lote_listo: 'Piloto: lote de 5 completo',
      C: 'Piezas expulsadas en el lote',
    },
    steps: { 0: 'Reposo (C a 0)', 1: 'Expulsando', 2: 'Recogiendo el expulsor (C + 1)', 3: 'Lote listo' },
  },
  'apilador-trampilla': {
    variables: {
      Marcha: 'Interruptor de marcha',
      Pila: 'Detector: tercera caja de la pila',
      b0: 'Final de carrera: trampilla cerrada',
      b1: 'Final de carrera: trampilla abierta',
      Cinta: 'Motor de la cinta',
      Abrir: 'Abrir la trampilla (se cierra por su peso)',
      C: 'Pilas descargadas',
      '1s/Pila': 'Pila vista durante 1 s (no una caja cayendo)',
    },
    steps: { 0: 'Parado', 1: 'Apilando', 2: 'Abriendo la trampilla (C + 1)', 3: 'Cerrándose' },
  },
  encapsulacion: {
    variables: {
      Marcha: 'Pulsador de marcha',
      Paro: 'Pulsador de paro (inmediato)',
      a0: 'Detector: cilindro A dentro',
      a1: 'Detector: cilindro A fuera',
      En_marcha: 'Piloto: en marcha',
      'A+': 'Electroválvula: sacar A',
      'A-': 'Electroválvula: meter A',
    },
    steps: { 0: 'Parado', 1: 'En marcha (encapsula G1)', 11: 'Sale A (enlace de activación)', 12: 'Entra A' },
  },
}
